#ifndef FINE_H
#define FINE_H
#include <string>

class Fine
{
private:
    int fine_id;
    int transaction_id;
    int user_id;
    int days_overdue;
    double fine_amount;
    std::string fine_date;
    bool is_paid;
    std::string payment_date; // format: YYYY-MM-DD HH:MM:SS (datetime)

public:

    // Constructors & Destructor
    Fine();

    // For creating a NEW fine (ID generated by DB later)
    Fine(int trans_id, int u_id, int days, double amount,
         const std::string &f_date, bool paid, const std::string &p_date);

    // For loading an EXISTING fine from the database
    Fine(int f_id, int trans_id, int u_id, int days, double amount,
         const std::string &f_date, bool paid, const std::string &p_date);

    ~Fine();

    // Getters
    int getFineId() const;
    int getTransactionId() const;
    int getUserId() const;
    int getDaysOverdue() const;
    double getFineAmount() const;
    std::string getFineDate() const;
    bool getIsPaid() const;
    std::string getPaymentDate() const;

    // Setters
    void setFineId(int id);
    void setTransactionId(int trans_id);
    void setUserId(int u_id);
    void setDaysOverdue(int days);
    void setFineAmount(double amount);
    void setFineDate(const std::string &f_date);
    void setIsPaid(bool paid);
    void setPaymentDate(const std::string &p_date);
};

#endif // FINE_H