#ifndef FUNDREQUEST_H
#define FUNDREQUEST_H
#include <string>

class FundRequest
{
private:
    int request_id;
    int user_id;
    double requested_amount;
    std::string request_date;  // format: YYYY-MM-DD HH:MM:SS (datetime)
    std::string status;        // e.g., 'PENDING', 'APPROVED', 'REJECTED'
    int admin_id;              // -1 or 0 can represent "No admin assigned yet"
    std::string approval_date; // format: YYYY-MM-DD HH:MM:SS (datetime)
    std::string admin_notes;

public:
    // Constructors & Destructor
    FundRequest();

    // For creating a NEW request (ID generated by DB later)
    FundRequest(int u_id, double amount, const std::string &r_date,
                const std::string &stat, int a_id, const std::string &a_date,
                const std::string &notes);

    // For loading an EXISTING request from the database
    FundRequest(int r_id, int u_id, double amount, const std::string &r_date,
                const std::string &stat, int a_id, const std::string &a_date,
                const std::string &notes);

    ~FundRequest();

    // Getters
    int getRequestId() const;
    int getUserId() const;
    double getRequestedAmount() const;
    std::string getRequestDate() const;
    std::string getStatus() const;
    int getAdminId() const;
    std::string getApprovalDate() const;
    std::string getAdminNotes() const;

    // Setters
    void setRequestId(int r_id);
    void setUserId(int u_id);
    void setRequestedAmount(double amount);
    void setRequestDate(const std::string &r_date);
    void setStatus(const std::string &stat);
    void setAdminId(int a_id);
    void setApprovalDate(const std::string &a_date);
    void setAdminNotes(const std::string &notes);
};

#endif // FUNDREQUEST_H
