#ifndef RESOURCE_H
#define RESOURCE_H
#include <string>

class Resource
{
private:
    int resource_id;
    std::string title;
    std::string author;
    std::string publisher;
    int publication_year;
    std::string isbn;
    int category_id;      // Foreign Key to Categories table
    int resource_type_id; // Foreign Key to ResourceTypes table
    int total_copies;     // DB Default: 1
    int available_copies; // DB Default: 1
    std::string description;
    std::string added_date; // format: YYYY-MM-DD HH:MM:SS
    bool is_active;         // DB Default: 1 (true)

public:
    // Constructors & Destructor
    Resource();

    // For creating a NEW resource (ID generated by DB later)
    Resource(const std::string &res_title, const std::string &res_author,
             const std::string &res_publisher, int pub_year,
             const std::string &res_isbn, int cat_id, int type_id,
             const std::string &desc, const std::string &add_date,
             int t_copies = 1, int a_copies = 1, bool active = true);

    // For loading an EXISTING resource from the database
    Resource(int res_id, const std::string &res_title, const std::string &res_author,
             const std::string &res_publisher, int pub_year,
             const std::string &res_isbn, int cat_id, int type_id,
             int t_copies, int a_copies, const std::string &desc,
             const std::string &add_date, bool active);

    ~Resource();

    // Getters
    int getResourceId() const;
    std::string getTitle() const;
    std::string getAuthor() const;
    std::string getPublisher() const;
    int getPublicationYear() const;
    std::string getIsbn() const;
    int getCategoryId() const;
    int getResourceTypeId() const;
    int getTotalCopies() const;
    int getAvailableCopies() const;
    std::string getDescription() const;
    std::string getAddedDate() const;
    bool getIsActive() const;

    // Setters
    void setResourceId(int res_id);
    void setTitle(const std::string &res_title);
    void setAuthor(const std::string &res_author);
    void setPublisher(const std::string &res_publisher);
    void setPublicationYear(int pub_year);
    void setIsbn(const std::string &res_isbn);
    void setCategoryId(int cat_id);
    void setResourceTypeId(int type_id);
    void setTotalCopies(int t_copies);
    void setAvailableCopies(int a_copies);
    void setDescription(const std::string &desc);
    void setAddedDate(const std::string &add_date);
    void setIsActive(bool active);
};

#endif // RESOURCE_H
