#ifndef CATEGORY_H
#define CATEGORY_H
#include <string>
class Category {
    private:
        int category_id;
        std::string name;
        std::string description;

public:

    // Constructors and Destructor

    Category();

    // For creating NEW categories (ID will be generated by DB later)
    Category(const std::string& name, const std::string& description);

    // Overloaded constructor with category_id for loading EXISTING categories from the database
    Category(int id, const std::string &name, const std::string &description);

    ~Category();


    // Getters
    int getCategoryId() const;
    std::string getName() const;
    std::string getDescription() const;

    // Setters
    void setCategoryId(int id);
    void setName(const std::string &name);
    void setDescription(const std::string &description);
    Category(int id, const std::string& name, const std::string& description);


};

#endif // CATEGORY_H
