#ifndef RESERVATION_H
#define RESERVATION_H
#include <string>

class Reservation
{
private:
    int reservation_id;
    int user_id;
    int resource_id;
    std::string reservation_date; // format: YYYY-MM-DD HH:MM:SS
    std::string expiry_date;      // format: YYYY-MM-DD HH:MM:SS
    bool is_fulfilled;            // DB Default: 0 (false)
    bool is_cancelled;            // DB Default: 0 (false)
    std::string status;           // DB Default: 'PENDING'

public:
    // Constructors & Destructor
    Reservation();
    
    // For creating a NEW reservation (ID generated by DB later)
    Reservation(int u_id, int res_id, const std::string &r_date,
                const std::string &e_date, bool fulfilled = false,
                bool cancelled = false, const std::string &stat = "PENDING");

    // For loading an EXISTING reservation from the database
    Reservation(int resv_id, int u_id, int res_id, const std::string &r_date,
                const std::string &e_date, bool fulfilled, bool cancelled,
                const std::string &stat);

    ~Reservation();

    // Getters
    int getReservationId() const;
    int getUserId() const;
    int getResourceId() const;
    std::string getReservationDate() const;
    std::string getExpiryDate() const;
    bool getIsFulfilled() const;
    bool getIsCancelled() const;
    std::string getStatus() const;

    // Setters
    void setReservationId(int resv_id);
    void setUserId(int u_id);
    void setResourceId(int res_id);
    void setReservationDate(const std::string &r_date);
    void setExpiryDate(const std::string &e_date);
    void setIsFulfilled(bool fulfilled);
    void setIsCancelled(bool cancelled);
    void setStatus(const std::string &stat);
};

#endif // RESERVATION_H
