#ifndef TRANSACTION_H
#define TRANSACTION_H
#include <string>

class Transaction
{
private:
    int transaction_id;
    int user_id;                    // Foreign Key to Users table
    int resource_id;                // Foreign Key to Resources table
    std::string issue_date;         // format: YYYY-MM-DD
    std::string due_date;           // format: YYYY-MM-DD
    std::string return_date;        // format: YYYY-MM-DD (Can be empty if not returned)
    double fine_amount;             // DB Default: 0.00
    bool is_returned;               // DB Default: 0 (false)
    bool is_overdue;                // DB Default: 0 (false)
    int renewal_count;              // DB Default: 0
    std::string transaction_status; // DB Default: 'ACTIVE'

public:
    // Constructors & Destructor
    Transaction();

    // For creating a NEW transaction (ID generated by DB later)
    Transaction(int u_id, int res_id, const std::string &i_date,
                const std::string &d_date, const std::string &r_date = "",
                double fine = 0.00, bool returned = false, bool overdue = false,
                int renewals = 0, const std::string &status = "ACTIVE");

    // For loading an EXISTING transaction from the database
    Transaction(int t_id, int u_id, int res_id, const std::string &i_date,
                const std::string &d_date, const std::string &r_date,
                double fine, bool returned, bool overdue,
                int renewals, const std::string &status);

    ~Transaction();

    // Getters
    int getTransactionId() const;
    int getUserId() const;
    int getResourceId() const;
    std::string getIssueDate() const;
    std::string getDueDate() const;
    std::string getReturnDate() const;
    double getFineAmount() const;
    bool getIsReturned() const;
    bool getIsOverdue() const;
    int getRenewalCount() const;
    std::string getTransactionStatus() const;

    // Setters
    void setTransactionId(int t_id);
    void setUserId(int u_id);
    void setResourceId(int res_id);
    void setIssueDate(const std::string &i_date);
    void setDueDate(const std::string &d_date);
    void setReturnDate(const std::string &r_date);
    void setFineAmount(double fine);
    void setIsReturned(bool returned);
    void setIsOverdue(bool overdue);
    void setRenewalCount(int renewals);
    void setTransactionStatus(const std::string &status);
};

#endif // TRANSACTION_H
