#ifndef USER_H
#define USER_H
#include "../additional_classes/Person.h" // Includes the base class header
#include <string>

class User : public Person
{
private:
    // We only declare the fields that make a User different from an Admin!
    int user_id;
    std::string address;
    std::string phone;
    double balance;                // DB Default: 0.00
    int membership_type_id;        // Foreign Key to MembershipTypes
    std::string registration_date; // format: YYYY-MM-DD HH:MM:SS

public:
    // Constructors & Destructor

    User();

    // For creating a NEW User (ID generated by DB later)
    User(const std::string &uname, const std::string &pass,
         const std::string &fname, const std::string &lname,
         const std::string &mail, const std::string &addr,
         const std::string &ph, int mem_type_id,
         const std::string &reg_date, double bal = 0.0, bool active = true);

    // For loading an EXISTING User from the database
    User(int u_id, const std::string &uname, const std::string &pass,
         const std::string &fname, const std::string &lname,
         const std::string &mail, const std::string &addr,
         const std::string &ph, double bal, int mem_type_id,
         const std::string &reg_date, bool active);

    ~User();

    // Getters (Only for the unique User variables)
    int getUserId() const;
    std::string getAddress() const;
    std::string getPhone() const;
    double getBalance() const;
    int getMembershipTypeId() const;
    std::string getRegistrationDate() const;

    // Setters (Only for the unique User variables)
    void setUserId(int u_id);
    void setAddress(const std::string &addr);
    void setPhone(const std::string &ph);
    void setBalance(double bal);
    void setMembershipTypeId(int mem_type_id);
    void setRegistrationDate(const std::string &reg_date);
};

#endif // USER_H
