#ifndef WISHLIST_H
#define WISHLIST_H
#include <string>

class Wishlist
{
private:
    int wishlist_id;
    int user_id;              // Foreign Key to Users table
    std::string title;
    std::string author;       // Can be empty if unknown
    std::string isbn;         // Can be empty if unknown
    int category_id;          // Foreign Key to Categories (0 or -1 if unknown)
    std::string request_date; // format: YYYY-MM-DD HH:MM:SS (datetime)
    std::string status;       // DB Default: 'PENDING'
    std::string admin_notes;

public:
    // Constructors & Destructor
    Wishlist();

    // For creating a NEW wishlist request (ID generated by DB later)
    Wishlist(int u_id, const std::string &req_title, const std::string &req_author,
             const std::string &req_isbn, int cat_id, const std::string &r_date,
             const std::string &notes = "", const std::string &stat = "PENDING");

    // For loading an EXISTING wishlist request from the database
    Wishlist(int w_id, int u_id, const std::string &req_title, const std::string &req_author,
             const std::string &req_isbn, int cat_id, const std::string &r_date,
             const std::string &stat, const std::string &notes);

    ~Wishlist();

    // Getters
    int getWishlistId() const;
    int getUserId() const;
    std::string getTitle() const;
    std::string getAuthor() const;
    std::string getIsbn() const;
    int getCategoryId() const;
    std::string getRequestDate() const;
    std::string getStatus() const;
    std::string getAdminNotes() const;

    // Setters
    void setWishlistId(int w_id);
    void setUserId(int u_id);
    void setTitle(const std::string &req_title);
    void setAuthor(const std::string &req_author);
    void setIsbn(const std::string &req_isbn);
    void setCategoryId(int cat_id);
    void setRequestDate(const std::string &r_date);
    void setStatus(const std::string &stat);
    void setAdminNotes(const std::string &notes);
};

#endif // WISHLIST_H
